import React,{useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ShieldCheck,UploadCloud,FileSearch,CheckCircle2,AlertTriangle,X,RotateCcw,ExternalLink}from'lucide-react';
import Tesseract from'tesseract.js';
import jsQR from'jsqr';
import*as pdfjsLib from'pdfjs-dist';
import pdfWorker from'pdfjs-dist/build/pdf.worker.min.mjs?url';
import'./styles.css';
pdfjsLib.GlobalWorkerOptions.workerSrc=pdfWorker;

const steps=['Reading document','Extracting text','Checking QR & patterns','Calculating risk'];
const clean=s=>s.toUpperCase().replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
function levenshtein(a,b){const row=[...Array(b.length+1).keys()];for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return row[b.length]}
function nameSimilarity(name,text){const target=clean(name),words=clean(text).split(' '),count=target.split(' ').length;let best=0;for(let size=Math.max(1,count-1);size<=count+1;size++)for(let i=0;i<=words.length-size;i++){const candidate=words.slice(i,i+size).join(' ');best=Math.max(best,1-levenshtein(target,candidate)/Math.max(target.length,candidate.length))}return Math.round(best*100)}
async function imageFromFile(file){
 if(file.type==='application/pdf'){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const page=await pdf.getPage(1);const viewport=page.getViewport({scale:2});const c=document.createElement('canvas');c.width=viewport.width;c.height=viewport.height;await page.render({canvasContext:c.getContext('2d'),viewport}).promise;return c;}
 const img=new Image();img.src=URL.createObjectURL(file);await img.decode();const c=document.createElement('canvas');const scale=Math.min(1,1800/img.width);c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(img.src);return c;
}
function hashCanvas(c){const x=document.createElement('canvas');x.width=9;x.height=8;const ctx=x.getContext('2d');ctx.drawImage(c,0,0,9,8);const d=ctx.getImageData(0,0,9,8).data;let bits='';for(let y=0;y<8;y++)for(let i=0;i<8;i++){const a=(d[(y*9+i)*4]+d[(y*9+i)*4+1]+d[(y*9+i)*4+2])/3,b=(d[(y*9+i+1)*4]+d[(y*9+i+1)*4+1]+d[(y*9+i+1)*4+2])/3;bits+=a>b?'1':'0'}return BigInt('0b'+bits).toString(16).padStart(16,'0')}
function inspect(c){const ctx=c.getContext('2d'),d=ctx.getImageData(0,0,c.width,c.height).data;let high=0,total=0;for(let i=0;i<d.length;i+=Math.max(4,Math.floor(d.length/24000/4)*4)){const mx=Math.max(d[i],d[i+1],d[i+2]),mn=Math.min(d[i],d[i+1],d[i+2]);if(mx-mn>120)high++;total++}return high/total>.18?'Medium':'Low'}
async function analyzeDocument(file,name,onProgress){const canvas=await imageFromFile(file);onProgress(1);const ocr=await Tesseract.recognize(canvas,'eng',{logger:m=>m.status==='recognizing text'&&onProgress(1,Math.round(m.progress*100))});onProgress(2);const ctx=canvas.getContext('2d');const qr=jsQR(ctx.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height);const text=clean(ocr.data.text);const ids=text.match(/(?:ID|NO|NUMBER|CERTIFICATE)\s*[:#-]?\s*([A-Z0-9-]{4,})/i);const similarity=nameSimilarity(name,text);onProgress(3);return{registeredName:name,ocrText:ocr.data.text,confidence:Math.round(ocr.data.confidence),nameFound:similarity>=82,nameSimilarity:similarity,certificateId:ids?.[1]||null,qrData:qr?.data||null,hash:hashCanvas(canvas),editingRisk:inspect(canvas),fileName:file.name}}

function Status({ok,children}){return <span className={'status '+(ok?'pass':'warn')}>{ok?<CheckCircle2/>:<AlertTriangle/>}{children}</span>}
function App(){const input=useRef();const[name,setName]=useState('');const[file,setFile]=useState();const[busy,setBusy]=useState(false);const[stage,setStage]=useState(0);const[pct,setPct]=useState(0);const[result,setResult]=useState();const[error,setError]=useState('');
 const choose=f=>{if(!f)return;if(!['image/png','image/jpeg','image/webp','application/pdf'].includes(f.type)||f.size>10*1024*1024){setError('Use a PNG, JPG, WebP, or PDF up to 10 MB.');return}setFile(f);setError('');setResult(null)};
 const run=async()=>{if(!name.trim()||!file){setError('Enter the registered student name and choose a certificate.');return}try{setBusy(true);setStage(0);const data=await analyzeDocument(file,name,(s,p=0)=>{setStage(s);setPct(p)});const response=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error('Analysis service unavailable');setResult(await response.json())}catch(e){setError(e.message||'Could not analyze this document.')}finally{setBusy(false)}};
 const reset=()=>{setFile();setResult();setError('');setStage(0);setPct(0)};
 return <><header><a className="brand" href="#"><span><ShieldCheck/></span>CertGuard</a><span className="v1">V1 · FRAUD SCREENING</span></header><main>
  <section className="hero"><div className="eyebrow"><span/>CERTIFICATE INTELLIGENCE</div><h1>Trust certificates.<br/><em>Verify the evidence.</em></h1><p>Fast, explainable fraud screening for student credentials—before they reach admin review.</p><div className="proof"><span><CheckCircle2/>On-device OCR</span><span><CheckCircle2/>Explainable score</span><span><CheckCircle2/>Privacy-first</span></div></section>
  <section className="workspace" aria-label="Certificate analyzer"><div className="panel-head"><div><small>NEW ANALYSIS</small><h2>Screen a certificate</h2></div><FileSearch/></div>{!result?<>
   <label className="field"><span>Registered student name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Ketan Rajendra Patil" disabled={busy}/><small>Compared with the name extracted from the certificate</small></label>
   <button className={'drop '+(file?'selected':'')} onClick={()=>input.current.click()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}} onDragOver={e=>e.preventDefault()} disabled={busy}><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>choose(e.target.files[0])}/>{file?<><CheckCircle2/><strong>{file.name}</strong><span>{(file.size/1024/1024).toFixed(2)} MB · Ready</span></>:<><UploadCloud/><strong>Drop certificate here</strong><span>or tap to browse · PNG, JPG, WebP, PDF · Max 10 MB</span></>}</button>
   {busy&&<div className="progress" role="status"><div><span>{steps[stage]}</span><b>{stage===1?pct+'%':stage*25+'%'}</b></div><i><u style={{width:`${stage===1?25+pct/4:stage*25}%`}}/></i><small>OCR can take a moment on the first run.</small></div>}
   {error&&<div className="error"><AlertTriangle/>{error}</div>}<button className="primary" onClick={run} disabled={busy}>{busy?'Analyzing…':'Analyze certificate'}<ShieldCheck/></button>
  </>:<Report r={result} reset={reset}/>}</section>
 </main><footer><span>Built for trustworthy student records.</span><span>OCR · QR · DUPLICATE · TAMPER SIGNALS</span></footer></>}
function Report({r,reset}){const level=r.riskScore<30?'Low':r.riskScore<65?'Review':'High';return <div className="report"><div className="score-row"><div className={'score '+level.toLowerCase()}><strong>{r.riskScore}</strong><span>/100 RISK</span></div><div><small>SCREENING RESULT</small><h2>{level} fraud risk</h2><p>{r.summary}</p></div></div><div className="checks"><div><span>Name match</span><Status ok={r.checks.nameMatch}>{r.checks.nameMatch?'Pass':'Review'}</Status></div><div><span>Certificate ID</span><Status ok={!!r.checks.certificateId}>{r.checks.certificateId||'Not found'}</Status></div><div><span>QR verification</span><Status ok={r.checks.qrStatus==='Pass'}>{r.checks.qrStatus}</Status></div><div><span>Duplicate match</span><Status ok={!r.checks.duplicate}>{r.checks.duplicate?'Possible match':'None'}</Status></div><div><span>Editing indicators</span><Status ok={r.checks.editingRisk==='Low'}>{r.checks.editingRisk}</Status></div><div><span>OCR confidence</span><Status ok={r.checks.ocrConfidence>=60}>{r.checks.ocrConfidence}%</Status></div></div>{r.checks.qrData&&<a className="qr" href={r.checks.qrData} target="_blank" rel="noreferrer">Open detected verification link <ExternalLink/></a>}<details><summary>View extracted text</summary><pre>{r.ocrText}</pre></details><button className="secondary" onClick={reset}><RotateCcw/>Analyze another</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
